server:
  port: 8762
eureka:
#  instance:
#    prefer-ip-address: true #是否优先使用ip地址作为主机名的标识
  client:
    serviceUrl:
      defaultZone: http://${my.eureka.host}:${my.eureka.port}/eureka/   #      defaultZone: http://WP_eureka:WPImNUxMg9lyzzB5u@localhost:8761/eureka/

#  instance:
#    lease-renewal-interval-in-seconds: 10      # 心跳时间，即服务续约间隔时间（缺省为30s）
#    lease-expiration-duration-in-seconds: 30  # 发呆时间，即服务续约到期时间（缺省为90s）
spring:
  application:
    name: eureka-client
